// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPumdToZbWtkZ95q-6-E0a4vuQfwCecZ0',
    appId: '1:482417964544:web:df0d5b7405497d4b9a4ae5',
    messagingSenderId: '482417964544',
    projectId: 'attendance-app-84a82',
    authDomain: 'attendance-app-84a82.firebaseapp.com',
    storageBucket: 'attendance-app-84a82.appspot.com',
    measurementId: 'G-KQBW8KF7KZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCcs2u9KXn1Jp601rhplA_T-N-yew5gic',
    appId: '1:482417964544:android:2838f2b47b1b664e9a4ae5',
    messagingSenderId: '482417964544',
    projectId: 'attendance-app-84a82',
    storageBucket: 'attendance-app-84a82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcys69o5gCFjIguGqeAxQN6sQsisMIuxs',
    appId: '1:482417964544:ios:6da0df359d18530b9a4ae5',
    messagingSenderId: '482417964544',
    projectId: 'attendance-app-84a82',
    storageBucket: 'attendance-app-84a82.appspot.com',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcys69o5gCFjIguGqeAxQN6sQsisMIuxs',
    appId: '1:482417964544:ios:6da0df359d18530b9a4ae5',
    messagingSenderId: '482417964544',
    projectId: 'attendance-app-84a82',
    storageBucket: 'attendance-app-84a82.appspot.com',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPumdToZbWtkZ95q-6-E0a4vuQfwCecZ0',
    appId: '1:482417964544:web:beafda09acba40fe9a4ae5',
    messagingSenderId: '482417964544',
    projectId: 'attendance-app-84a82',
    authDomain: 'attendance-app-84a82.firebaseapp.com',
    storageBucket: 'attendance-app-84a82.appspot.com',
    measurementId: 'G-Y5YD7JHW87',
  );
}
